CREATE DATABASE DBGENESIS

USE DBGENESIS

CREATE TABLE IF NOT EXISTS tasa_cambio(
 id_peticion BIGINT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
 fecha DATE NOT NULL,
 hora TIME NOT NULL,
 tasa_venta DECIMAL(10, 5) NOT NULL,
 tasa_compra DECIMAL(10, 5) NOT NULL
);